"""
SQLAlchemy ORM models for the ESI Checker application.
"""
import json
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean, Column, DateTime, Float, ForeignKey,
    Integer, String, Text,
)
from sqlalchemy.orm import relationship

from database.db import Base


def _now():
    return datetime.utcnow()


# ---------------------------------------------------------------------------
# Recruiter (corp officer) accounts
# ---------------------------------------------------------------------------

class Recruiter(Base):
    __tablename__ = "recruiters"

    id = Column(Integer, primary_key=True, index=True)
    character_id = Column(Integer, unique=True, nullable=False, index=True)
    character_name = Column(String(100), nullable=False)
    corporation_id = Column(Integer, nullable=False)
    is_admin = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), default=_now)
    last_login = Column(DateTime(timezone=True), default=_now)

    actions = relationship("AuditLog", back_populates="recruiter")


# ---------------------------------------------------------------------------
# Invite links (generated by recruiters for applicants)
# ---------------------------------------------------------------------------

class InviteLink(Base):
    __tablename__ = "invite_links"

    id = Column(Integer, primary_key=True, index=True)
    token = Column(String(64), unique=True, nullable=False, index=True)
    created_by = Column(Integer, ForeignKey("recruiters.id"), nullable=False)
    note = Column(String(200), default="")          # e.g. "For John Doe"
    is_used = Column(Boolean, default=False)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), default=_now)

    application = relationship("Application", back_populates="invite", uselist=False)


# ---------------------------------------------------------------------------
# Application — one per recruit attempt
# ---------------------------------------------------------------------------

class Application(Base):
    __tablename__ = "applications"

    id = Column(Integer, primary_key=True, index=True)
    invite_id = Column(Integer, ForeignKey("invite_links.id"), nullable=False)

    character_id = Column(Integer, nullable=False, index=True)
    character_name = Column(String(100), nullable=False)

    # Encrypted EVE SSO tokens
    access_token_enc = Column(Text, nullable=False)
    refresh_token_enc = Column(Text, nullable=False)
    token_expires_at = Column(Integer, nullable=False)  # Unix timestamp

    # Analysis results
    status = Column(String(20), default="pending")  # pending|fetching|scored|approved|denied|hold
    trust_score = Column(Integer, nullable=True)
    score_band = Column(String(10), nullable=True)  # green|yellow|orange|red
    recommendation = Column(Text, nullable=True)

    # Full ESI data and analysis stored as JSON text
    esi_data_json = Column(Text, nullable=True)
    red_flags_json = Column(Text, nullable=True)
    score_breakdown_json = Column(Text, nullable=True)
    zkb_data_json = Column(Text, nullable=True)

    # Recruiter decision
    decision = Column(String(20), nullable=True)    # approved|denied|hold
    decision_by = Column(Integer, ForeignKey("recruiters.id"), nullable=True)
    recruiter_notes = Column(Text, default="")
    decided_at = Column(DateTime(timezone=True), nullable=True)

    submitted_at = Column(DateTime(timezone=True), default=_now)
    scored_at = Column(DateTime(timezone=True), nullable=True)

    invite = relationship("InviteLink", back_populates="application")
    logs = relationship("AuditLog", back_populates="application")

    # -- Helpers --

    def get_esi_data(self) -> dict:
        return json.loads(self.esi_data_json) if self.esi_data_json else {}

    def set_esi_data(self, data: dict):
        self.esi_data_json = json.dumps(data)

    def get_red_flags(self) -> list:
        return json.loads(self.red_flags_json) if self.red_flags_json else []

    def set_red_flags(self, flags: list):
        # Convert RedFlag dataclasses to dicts for JSON storage
        self.red_flags_json = json.dumps([
            {"category": f.category, "severity": f.severity,
             "message": f.message, "detail": f.detail}
            for f in flags
        ])

    def get_score_breakdown(self) -> dict:
        return json.loads(self.score_breakdown_json) if self.score_breakdown_json else {}

    def set_score_breakdown(self, breakdown: dict):
        self.score_breakdown_json = json.dumps(breakdown)


# ---------------------------------------------------------------------------
# Hostile watchlist — corps/alliances to flag
# ---------------------------------------------------------------------------

class WatchlistEntry(Base):
    __tablename__ = "watchlist"

    id = Column(Integer, primary_key=True, index=True)
    entity_id = Column(Integer, unique=True, nullable=False, index=True)
    entity_type = Column(String(20), nullable=False)    # "corporation" | "alliance"
    entity_name = Column(String(100), nullable=False)
    reason = Column(String(200), default="")
    added_by = Column(Integer, ForeignKey("recruiters.id"), nullable=False)
    added_at = Column(DateTime(timezone=True), default=_now)


# ---------------------------------------------------------------------------
# Audit log
# ---------------------------------------------------------------------------

class AuditLog(Base):
    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True, index=True)
    recruiter_id = Column(Integer, ForeignKey("recruiters.id"), nullable=True)
    application_id = Column(Integer, ForeignKey("applications.id"), nullable=True)
    action = Column(String(50), nullable=False)     # e.g. "approved", "invite_created"
    detail = Column(Text, default="")
    timestamp = Column(DateTime(timezone=True), default=_now)

    recruiter = relationship("Recruiter", back_populates="actions")
    application = relationship("Application", back_populates="logs")
